// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaeClass.Models;

namespace RaeClass.Migrations
{
    [DbContext(typeof(RaeClassContext))]
    [Migration("20181119025015_raedb1")]
    partial class raedb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RaeClass.Models.ListenContent", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FCreateTime");

                    b.Property<string>("FJsonData");

                    b.Property<DateTime>("FModifyTime");

                    b.HasKey("FId");

                    b.ToTable("ListenContentSet");
                });

            modelBuilder.Entity("RaeClass.Models.ReadContent", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FCreateTime");

                    b.Property<string>("FJsonData");

                    b.Property<DateTime>("FModifyTime");

                    b.HasKey("FId");

                    b.ToTable("ReadContentSet");
                });
#pragma warning restore 612, 618
        }
    }
}
