// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaeClass.Models;

namespace RaeClass.Migrations
{
    [DbContext(typeof(RaeClassContext))]
    partial class RaeClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RaeClass.Models.BaseFormContent", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FContentType");

                    b.Property<DateTime>("FCreateTime");

                    b.Property<string>("FDocStatus");

                    b.Property<string>("FJsonData");

                    b.Property<string>("FLevel");

                    b.Property<DateTime>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNumber");

                    b.HasKey("FId");

                    b.ToTable("BaseFormContent","dbo");
                });

            modelBuilder.Entity("RaeClass.Models.SerialNumber", b =>
                {
                    b.Property<int>("FID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FContentType");

                    b.Property<int>("FCurrentGeneratedIndex");

                    b.Property<DateTime>("FModifyTime");

                    b.HasKey("FID");

                    b.ToTable("SerialNumber","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
